### ISSUE TITLE
Standardize plugin artifact names

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-plugins#47]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/41#issuecomment-858139926

Now that Dashboards defaults to `kebab-case` for installed plugins, shall we finalize naming conventions for the build zips for Dashboards plugins? 

Current zip convention: `<pluginName>Dashboards-x.zip` (e.g., anomalyDetectionDashboards-1.0.0.0-rc1.zip`)

New ideas:
Option 1: identical to existing name, but in `kebab-case`: `<plugin-name>-dashboards-x.zip` (e.g., `anomaly-detection-dashboards-1.0.0.0-rc1.zip`.
Option 2: same convention as OpenSearch plugins, but replacing `opensearch` with `dashboards`: `dashboards-<plugin-name>-x.zip` (e.g., `dashboards-anomaly-detection-1.0.0.0-rc1.zip` (this was mentioned [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/322#issuecomment-840074136) as well)

Any thoughts here? I think either make sense. Option 1 will keep consistency with the existing plugin IDs which are following the camelcase convention of `<pluginNameDashboards>` (note that this could be changed to something like `dashboardsPluginName`, but will require more code changes & testing). Option 2 will keep consistency with OpenSearch plugin names, in regards to the zips at least.

**Comment by dblock** [comment]
I feel strongly that no files or folder names should be using capitalized letters because it's only a matter of time till someone runs this on a case-sensitive system and scripts something that doesn't match capitalization. Particularly fun with `rm -rf`. So definitely 💯 on kebab-casing everything, but I don't think it's controversial.

I think the name should match the plugin default folder name. So that's option 2, right?

**Comment by ohltyler** [comment]
So the IDs still have to be camelCase for now as required by Dashboards plugin contract (it is being worked on).

If by default folder name, you mean the folder name after installing on Dashboards, then that is option 1 (Dashboards converts the required camelCase ID and converts to kebab-case). Since all plugins are following the ID convention of `<pluginName>Dashboards`, this option would be consistent in the installed folder names that would have the convention `<plugin-name>-dashboards`. 

Option 2 is more about changing the zip naming conventions to be consistent with the OpenSearch plugins. If only changing the zip, it would be inconsistent with the underlying plugin ID. Additionally, we could change the name of the plugin ID, but that would require more work and would break some plugin dependencies that are referencing other plugins' names.

**Comment by dblock** [comment]
I am definitely not advocating to changing the plugin ID.

So I think I'm saying I prefer option 1 for all the reasons you're describing in option 2. Basically I am saying if a plugin gets installed into a folder called `plugin-folder`, then I expect to find `plugin-folder` in the zip name. I don't think there's anything magical about the word "dashboards". If the plugin folder is `security-dashboards` I'd want the zip to be called `security-dashboards-1.0.0....`. 

Also cc: @VachaShah who was looking at related issues

**Comment by dblock** [comment]
@ohltyler either way, do you want to take on this issue?

**Comment by ohltyler** [comment]
With option 2, we could also make consistent with the folder name, if we changed both (1) the zip naming convention and (2) the plugin ID naming convention, since the ID determines the folder name.

I think I prefer option 1 for now, since it introduces the lowest risk. We can change the plugin ID once it is able to support kebab-case, rather than having to change it now, and then change it again later.

Sure, I can take this. Going with option 1 will require no work from Dashboards, just small changes in the plugin build scripts to alter the build zip.

**Comment by dblock** [comment]
I'd like the zip change for GA I think.

**Comment by ohltyler** [comment]
Agreed. Will be little effort for the plugins.

**Comment by ohltyler** [comment]
@camerski @peterzhuamazon any concerns on changing Dashboards plugins to the new convention of option 1 (`<plugin-name>-dashboards-<version>.zip`? Same wording as before, but in kebab-case instead of camelCase. Want to provide a heads-up before broadcasting this to folks working on the Dashboards plugins.

**Comment by ohltyler** [comment]
As discussed offline, will go ahead with these naming changes. Will create a PR to finalize this.

**Comment by ohltyler** [comment]
@dblock @saratvemulapalli  Have opened #56 to address this. Can't add reviewers here either, please have a look when you have a moment.

**Comment by saratvemulapalli** [comment]
> @dblock @saratvemulapalli Have opened #56 to address this. Can't add reviewers here either, please have a look when you have a moment.

Thanks Tyler. Added @VachaShah as well to review as she worked on this.

**Comment by saratvemulapalli** [comment]
@dblock any more action items here or can we close this?

**Comment by dblock** [comment]
If building all plugins right now generates the correct name, we can close. @ohltyler would know?

**Comment by ohltyler** [comment]
I've let plugins owners know of the changes, but since this was not finalized & PR wasn't merged until a few hours ago i don't think all of the plugins have made the changes yet.

If we just consider this issue related to finalizing the convention, we can close.
