### ISSUE TITLE
Add automated license header checks 

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-plugins#49]
We have to standardize the way to develop on opensearch-project. 
We should be able to have license header checks.

**Comment by ketanv3** [comment]
OpenSearch plugins' source code should include a valid SPDX license header (along with the existing license headers, if any).

Further, plugins should enable the 'licenseHeaders' check in their build.gradle file if it was previously disabled.
Example - https://github.com/opensearch-project/asynchronous-search/blob/main/build.gradle#L117

Plugin authors can also use IntelliJ's [Copyright](https://www.jetbrains.com/help/idea/copyright.html) functionality to auto-generate this license header. This Copyright profile can be made a part of the plugin repo itself so that headers are consistently generated for all contributors.

**Comment by dblock** [comment]
@ketanv3 any interest in picking this up, writing it up in this repo and helping track it across plugins?

**Comment by ketanv3** [comment]
@dblock Sure, please assign this to me.

**Comment by ketanv3** [comment]
Plugin checklist:
- [ ] alerting
- [ ] anomaly-detection
- [ ] asynchronous-search
- [ ] common-utils
- [ ] data-prepper
- [ ] index-management
- [ ] job-scheduler
- [ ] k-NN
- [ ] performance-analyzer
- [ ] performance-analyzer-rca
- [ ] security
- [ ] sql

**Comment by saratvemulapalli** [comment]
@ketanv3 thanks for taking care of this. You don't have to make changes in every plugin. 
Let the plugins own it. 

Can you document the process on how to setup the license header checks in this repository and we can take @ MMakaria 's help to drive it across all the plugins to make sure all plugins will follow the steps you have recommended.

**Comment by ketanv3** [comment]
@saratvemulapalli Sure! I'll raise a PR documenting this process.

**Comment by saratvemulapalli** [comment]
Closing this as documentation for setting up license headers is done.
Plugin owners can follow the process recommended in https://github.com/opensearch-project/opensearch-plugins/blob/main/HEADERS.md#automated-license-headers-checks
